# Generated by Django 2.0.5 on 2018-05-15 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('team', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('twitter', models.CharField(max_length=200)),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.RosterFile')),
            ],
        ),
    ]
