# Generated by Django 2.0.5 on 2018-05-15 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0004_result_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('screen_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('profile_banner_url', models.URLField()),
                ('profile_image_url', models.URLField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.Player')),
            ],
        ),
        migrations.RemoveField(
            model_name='result',
            name='player',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
