# Generated by Django 2.0.5 on 2018-05-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0005_auto_20180515_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterresult',
            name='profile_banner_url',
            field=models.URLField(blank=True, default='https://pbs.twimg.com/profile_banners/17874544/1499274456', null=True),
        ),
    ]
