# Generated by Django 2.0.5 on 2018-05-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0006_auto_20180515_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='twitter',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
