# Generated by Django 2.0.5 on 2018-05-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0007_auto_20180515_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='rosterfile',
            name='name',
            field=models.CharField(default='Roster', max_length=50),
        ),
    ]
