# Generated by Django 2.0.5 on 2018-05-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0008_rosterfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='twitter_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='twitterresult',
            name='user_id',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
