# Generated by Django 2.0.5 on 2018-05-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0009_auto_20180515_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='twitter',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
