# Generated by Django 2.0.5 on 2018-05-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0010_auto_20180515_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterresult',
            name='friend',
            field=models.BooleanField(default=False),
        ),
    ]
