# Generated by Django 2.0.5 on 2018-05-16 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0011_twitterresult_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.Player')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.RosterFile')),
            ],
        ),
    ]
