# Generated by Django 2.0.5 on 2018-05-16 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0012_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Roster', max_length=50)),
                ('document', models.FileField(upload_to='documents/')),
                ('name_col', models.CharField(max_length=1)),
                ('twitter_col', models.CharField(max_length=1)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='twitterresult',
            options={'ordering': ['-friend']},
        ),
        migrations.AlterField(
            model_name='friend',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.Roster'),
        ),
        migrations.AlterField(
            model_name='player',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.Roster'),
        ),
        migrations.DeleteModel(
            name='RosterFile',
        ),
    ]
