# Generated by Django 2.0.5 on 2018-05-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0013_auto_20180516_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='city',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.RemoveField(
            model_name='player',
            name='state',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
    ]
