# Generated by Django 2.0.5 on 2018-05-16 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0014_auto_20180516_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='twitter_col',
        ),
    ]
