# Generated by Django 2.0.5 on 2018-05-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0015_remove_roster_twitter_col'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roster',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='roster',
            name='min_followers',
            field=models.IntegerField(default=100),
        ),
    ]
