# Generated by Django 2.0.5 on 2018-05-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0016_auto_20180516_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='twitter_col',
            field=models.CharField(default='H', max_length=1),
            preserve_default=False,
        ),
    ]
